from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
import connector
import dataBarang

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(696, 480)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 101))
        self.label.setStyleSheet("background-color: #647381;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 111, 101))
        self.label_2.setStyleSheet("image: url(:/newPrefix/images__1_-removebg-preview.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 110, 491, 351))
        self.label_4.setStyleSheet("background: #647381;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(120, 130, 451, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 160, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background: #EBEBEB;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 210, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background: #EBEBEB;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 270, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background: #EBEBEB;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 320, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background: #EBEBEB;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.PB_tambah = QtWidgets.QPushButton(Dialog)
        self.PB_tambah.setGeometry(QtCore.QRect(120, 370, 381, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_tambah.setFont(font)
        self.PB_tambah.setStyleSheet("background: #AAB0B6;\n"
"")
        self.PB_tambah.setObjectName("PB_tambah")
        self.PB_dataBarang = QtWidgets.QPushButton(Dialog)
        self.PB_dataBarang.setGeometry(QtCore.QRect(120, 410, 381, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_dataBarang.setFont(font)
        self.PB_dataBarang.setStyleSheet("background: #AAB0B6;")
        self.PB_dataBarang.setObjectName("PB_dataBarang")
        self.PB_kembali2 = QtWidgets.QPushButton(Dialog)
        self.PB_kembali2.setGeometry(QtCore.QRect(510, 370, 61, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_kembali2.setFont(font)
        self.PB_kembali2.setStyleSheet("background: #AAB0B6;")
        self.PB_kembali2.setObjectName("PB_kembali2")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.lineEdit.editingFinished.connect(self.checkProduk)
        self.PB_tambah.clicked.connect(self.simpanBarang)
        self.PB_dataBarang.clicked.connect(self.lihatBarang)
        self.clear()
        self.retranslateUi(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Barang"))
        self.label_5.setText(_translate("Dialog", "Barang"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "ID Barang"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Nama Barang"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Harga Barang"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Stok Barang"))
        self.PB_tambah.setText(_translate("Dialog", "TAMBAH"))
        self.PB_dataBarang.setText(_translate("Dialog", "LIHAT DATA BARANG"))
        self.PB_kembali2.setText(_translate("Dialog", "KEMBALI"))

    def lihatBarang(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = dataBarang.Ui_Dialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()

    def clear(self):
        self.lineEdit.setDisabled(False)
        self.lineEdit_2.setDisabled(True)
        self.lineEdit_3.setDisabled(True)
        self.lineEdit_4.setDisabled(True)
        self.PB_tambah.setDisabled(True)
        self.PB_tambah.setText("TAMBAH")

        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")
        self.lineEdit_4.setText("")

    def checkProduk(self):
        self.lineEdit_2.setDisabled(False)
        self.lineEdit_3.setDisabled(False)
        self.lineEdit_4.setDisabled(False)
        self.PB_tambah.setDisabled(False)
        idbarang = self.lineEdit.text()
        cursor = connector.cnx.cursor()

        query = ("SELECT * FROM produk WHERE id = %s")
        cursor.execute(query, (idbarang,))
        results = cursor.fetchall()
        if cursor.rowcount == 0:
            print("Tidak ada data")
        else:
            self.lineEdit.setDisabled(True)
            for data in results:
                self.lineEdit_2.setText(data[1])
                self.lineEdit_3.setText(str(data[2]))
                self.lineEdit_4.setText(str(data[3]))

            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Anda ingin melakukan apa?")
            msgBox.setWindowTitle("Data sudah ada")
            msgBox.addButton(QPushButton("Update"), QMessageBox.YesRole)
            msgBox.addButton(QPushButton("Hapus"), QMessageBox.NoRole)
            returnValue = msgBox.exec()

            if returnValue == 0:
                #update
                self.PB_tambah.setText("UPDATE")
            else:
                #delete
                query = ("DELETE FROM produk WHERE id = %s")
                cursor.execute(query, (idbarang,))
                connector.cnx.commit()
                self.clear()
        cursor.close()

    def simpanBarang(self):
        id = self.lineEdit.text()
        nama = self.lineEdit_2.text()
        harga = self.lineEdit_3.text()
        stok = self.lineEdit_4.text()

        if nama != "" and harga != "" and harga != "" and stok != "":
            if self.PB_tambah.text() == "TAMBAH":
                print("Insert")
                cursor = connector.cnx.cursor()
                val = (id, nama, harga, stok)
                query = ("INSERT INTO produk VALUES (%s, %s, %s, %s)")
                cursor.execute(query, val)
                connector.cnx.commit()
                cursor.close()
            else:
                print("Update")
                cursor = connector.cnx.cursor()
                val = (nama, harga, stok, id)
                query = ("UPDATE produk SET nama=%s, harga=%s, stok=%s WHERE id=%s")
                cursor.execute(query, val)
                connector.cnx.commit()
                cursor.close()

        self.clear()

        

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
