# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(696, 480)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 101))
        self.label.setStyleSheet("background-color: #647381;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 111, 101))
        self.label_2.setStyleSheet("image: url(:/newPrefix/images__1_-removebg-preview.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 420, 701, 81))
        self.label_4.setStyleSheet("background-color: #647381;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(-30, 100, 811, 321))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/turnamen-mobile-legends-holland-cafe_20180423_203207.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.PB_transaksi = QtWidgets.QPushButton(Dialog)
        self.PB_transaksi.setGeometry(QtCore.QRect(20, 440, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_transaksi.setFont(font)
        self.PB_transaksi.setStyleSheet("background: #AAB0B6;")
        self.PB_transaksi.setObjectName("PB_transaksi")
        self.PB_barang = QtWidgets.QPushButton(Dialog)
        self.PB_barang.setGeometry(QtCore.QRect(190, 440, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_barang.setFont(font)
        self.PB_barang.setStyleSheet("background: #AAB0B6;")
        self.PB_barang.setObjectName("PB_barang")
        self.PB_data = QtWidgets.QPushButton(Dialog)
        self.PB_data.setGeometry(QtCore.QRect(350, 440, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_data.setFont(font)
        self.PB_data.setStyleSheet("background: #AAB0B6;")
        self.PB_data.setObjectName("PB_data")
        self.PB_hiburan = QtWidgets.QPushButton(Dialog)
        self.PB_hiburan.setGeometry(QtCore.QRect(510, 440, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_hiburan.setFont(font)
        self.PB_hiburan.setStyleSheet("background: #AAB0B6;")
        self.PB_hiburan.setObjectName("PB_hiburan")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Dashboard"))
        self.PB_transaksi.setText(_translate("Dialog", "TRANSAKSI"))
        self.PB_barang.setText(_translate("Dialog", "BARANG"))
        self.PB_data.setText(_translate("Dialog", "DATA"))
        self.PB_hiburan.setText(_translate("Dialog", "HIBURAN"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
