# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import connector

class Ui_Dialog(object):
    products = []
    tmpProduct = ()
    sudahAda = False
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(696, 480)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 101))
        self.label.setStyleSheet("background-color: #647381;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 111, 101))
        self.label_2.setStyleSheet("image: url(:/newPrefix/images__1_-removebg-preview.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 110, 491, 361))
        self.label_4.setStyleSheet("background: #647381;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.LE_customer = QtWidgets.QLineEdit(Dialog)
        self.LE_customer.setGeometry(QtCore.QRect(120, 150, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LE_customer.setFont(font)
        self.LE_customer.setStyleSheet("background: #EBEBEB;")
        self.LE_customer.setObjectName("LE_customer")
        self.LE_idBarang = QtWidgets.QLineEdit(Dialog)
        self.LE_idBarang.setGeometry(QtCore.QRect(120, 190, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LE_idBarang.setFont(font)
        self.LE_idBarang.setStyleSheet("background: #EBEBEB;")
        self.LE_idBarang.setObjectName("LE_idBarang")
        self.LE_jumlahBarang = QtWidgets.QLineEdit(Dialog)
        self.LE_jumlahBarang.setGeometry(QtCore.QRect(350, 190, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LE_jumlahBarang.setFont(font)
        self.LE_jumlahBarang.setStyleSheet("background: #EBEBEB;")
        self.LE_jumlahBarang.setObjectName("LE_jumlahBarang")
        self.LE_daftarBarang = QtWidgets.QTextEdit(Dialog)
        self.LE_daftarBarang.setGeometry(QtCore.QRect(120, 230, 451, 151))
        self.LE_daftarBarang.setStyleSheet("background: #EBEBEB;")
        self.LE_daftarBarang.setObjectName("LE_daftarBarang")
        self.PB_beli = QtWidgets.QPushButton(Dialog)
        self.PB_beli.setGeometry(QtCore.QRect(120, 390, 381, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.PB_beli.setFont(font)
        self.PB_beli.setStyleSheet("background: #AAB0B6;")
        self.PB_beli.setObjectName("PB_beli")
        self.PB_dataTransaksi = QtWidgets.QPushButton(Dialog)
        self.PB_dataTransaksi.setGeometry(QtCore.QRect(120, 430, 381, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_dataTransaksi.setFont(font)
        self.PB_dataTransaksi.setStyleSheet("background: #AAB0B6;")
        self.PB_dataTransaksi.setObjectName("PB_dataTransaksi")
        self.PB_kembali = QtWidgets.QPushButton(Dialog)
        self.PB_kembali.setGeometry(QtCore.QRect(510, 390, 61, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_kembali.setFont(font)
        self.PB_kembali.setStyleSheet("background: #AAB0B6;")
        self.PB_kembali.setObjectName("PB_kembali")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 120, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(120, 130, 451, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")

        self.LE_idBarang.editingFinished.connect(self.getBarang)
        self.LE_jumlahBarang.editingFinished.connect(self.addBarang)
        self.disableJmlBarang()
        self.LE_customer.setFocus()
        self.LE_daftarBarang.setText("ID\tNAMA\t\tQTY\tHARGA")
        self.PB_beli.clicked.connect(self.beliBang)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Transaksi"))
        self.LE_customer.setPlaceholderText(_translate("Dialog", "Customer"))
        self.LE_idBarang.setPlaceholderText(_translate("Dialog", "Masukkan ID Barang"))
        self.LE_jumlahBarang.setPlaceholderText(_translate("Dialog", "Masukkan Jumlah Barang"))
        self.PB_beli.setText(_translate("Dialog", "BELI"))
        self.PB_dataTransaksi.setText(_translate("Dialog", "LIHAT DATA TRANSAKSI"))
        self.PB_kembali.setText(_translate("Dialog", "KEMBALI"))
        self.label_5.setText(_translate("Dialog", "Transaksi"))

    def disableJmlBarang(self):
        self.LE_jumlahBarang.setDisabled(True)
        self.LE_idBarang.setFocus()
        self.LE_idBarang.setText("")
        self.LE_jumlahBarang.setText("")

    def enableJmlBarang(self):
        self.LE_jumlahBarang.setDisabled(False)
        self.LE_jumlahBarang.setFocus()

    def getBarang(self):
        cursor = connector.cnx.cursor()
        idbarang = self.LE_idBarang.text()
        query = ("SELECT * FROM produk WHERE id = %s")
        cursor.execute(query, (idbarang,))
        results = cursor.fetchall()
        
        if cursor.rowcount == 0:
            print("Tidak ada data")
            self.LE_idBarang.setFocus()
        else:
            
            for data in results:
                self.tmpProduct = data
                for products in self.products:
                    if products[0] == data[0]:
                        self.sudahAda = True

            if self.sudahAda:
                print("Sudah ada")
                self.tmpProduct = ()
                self.sudahAda = False
                self.LE_idBarang.setFocus()
            else:
                self.enableJmlBarang()
        cursor.close()

    def addBarang(self):
        jmlBarang = self.LE_jumlahBarang.text()
        if jmlBarang != "":
            barang = "ID\tNAMA\t\tQTY\tHARGA"
            idBarang = self.LE_idBarang.text()
            self.products.append((idBarang, jmlBarang, self.tmpProduct[1],  self.tmpProduct[2]))

            for product in self.products:
                data = '\n{}\t{}\t\t{}\t{}'.format(product[0], product[2], product[1], product[3])
                barang+=data
                print(product[0], product[1], product[2])
                self.LE_daftarBarang.setText(barang)
            self.disableJmlBarang()

    def beliBang(self):
        customer = self.LE_customer.text()
        jmlBarang = 0
        total = 0
        for product in self.products:
            total += int(product[1]) * int(product[3])
            jmlBarang = jmlBarang + 1

        print(self.products)
        print(total, jmlBarang)

        cursor = connector.cnx.cursor()
        val = (customer, jmlBarang, total)
        query = ("INSERT INTO transaksi VALUES (null, %s, %s, %s)")
        cursor.execute(query, val)
        connector.cnx.commit()
        cursor.close()

        self.clear()

    def clear(self):
        self.disableJmlBarang()
        self.LE_daftarBarang.setText("ID\tNAMA\t\tQTY\tHARGA")
        self.LE_customer.setText("")
        self.LE_customer.setFocus()

import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
